//! `rausu init` subcommand and config file template.

use anyhow::{bail, Result};
use std::path::{Path, PathBuf};

use rausu::config::paths::default_config_path;

/// Minimal but fully commented YAML template written by `rausu init`.
pub const CONFIG_TEMPLATE: &str = r#"# rausu — LLM API Gateway configuration
#
# Auto-generated by `rausu init`.  Edit this file and run `rausu` to start.
#
# Environment variable interpolation: ${VAR_NAME}
# CLI value overrides:                RAUSU__SERVER__PORT=8080

# ── Server ────────────────────────────────────────────────────────────────────
server:
  host: 127.0.0.1   # use 0.0.0.0 to expose on the network
  port: 4000

# ── Logging ───────────────────────────────────────────────────────────────────
logging:
  level: info        # trace | debug | info | warn | error
  format: pretty     # json (structured) | pretty (human-readable)

# ── Authentication ────────────────────────────────────────────────────────────
#
# Protect your proxy with API key authentication when exposed on the network.
# mode: disabled (default) — no auth required
# mode: static   — require a valid Bearer token from the list below
#
# Key prefix convention: rausu-sk-<random>
auth:
  mode: disabled
  # keys:
  #   - name: "my-laptop"
  #     key: "rausu-sk-change-me"
  #   - name: "remote-client"
  #     key: "${RAUSU_API_KEY}"

# ── Models ────────────────────────────────────────────────────────────────────
#
# Each entry maps a virtual model name (what clients send) to one or more
# provider deployments.  Uncomment the sections you need.
models:

  # ── ChatGPT subscription (Plus / Pro / Max — no API key required) ──────────
  # Uses your ChatGPT OAuth session.
  # token_source: auto  →  tries CHATGPT_ACCESS_TOKEN env var first,
  #                        then ~/.config/rausu/chatgpt-auth.json
  #
  # - name: gpt-5
  #   providers:
  #     - provider: chatgpt-subscription
  #       model: gpt-5.4
  #       token_source: auto

  # ── GitHub Copilot (subscription — no API key required) ───────────────────
  # Token loaded from ~/.config/github-copilot/hosts.json (written by
  # `gh auth login` or the Copilot VS Code / JetBrains extension).
  # Claude models → native Anthropic Messages API passthrough.
  # GPT models    → translated from Chat Completions format.
  #
  # - name: claude-opus-4-6
  #   providers:
  #     - provider: github-copilot
  #       model: claude-opus-4.6

  # ── DeepSeek (OpenAI-compatible) ──────────────────────────────────────────
  # - name: deepseek-chat
  #   providers:
  #     - provider: openai
  #       model: deepseek-chat
  #       base_url: https://api.deepseek.com/v1
  #       api_key: "${DEEPSEEK_API_KEY}"

  # ── Ollama (local — no API key required) ──────────────────────────────────
  # - name: llama3
  #   providers:
  #     - provider: openai
  #       model: llama3
  #       base_url: http://localhost:11434/v1
  #       api_key: ollama
"#;

/// Write [`CONFIG_TEMPLATE`] to `target`.
///
/// Creates parent directories as needed.  Returns an error if the file already
/// exists and `force` is `false`.
pub fn write_template(target: &Path, force: bool) -> Result<()> {
    if target.exists() && !force {
        bail!(
            "Config file already exists at {path}.\nUse --force to overwrite.",
            path = target.display()
        );
    }
    if let Some(parent) = target.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(target, CONFIG_TEMPLATE)?;
    Ok(())
}

/// Execute the `rausu init` subcommand.
///
/// Writes the template config to `path` (or the XDG default if `None`).
/// If the file already exists and `force` is `false`, prints a message and
/// exits cleanly without overwriting.
pub fn run_init(path: Option<&str>, force: bool) -> Result<()> {
    let target: PathBuf = path.map(PathBuf::from).unwrap_or_else(default_config_path);
    let already_existed = target.exists();

    if already_existed && !force {
        println!("Config file already exists at: {}", target.display());
        println!("Use --force to overwrite.");
        return Ok(());
    }

    write_template(&target, force)?;

    if already_existed {
        println!("Overwritten: {}", target.display());
    } else {
        println!("Created: {}", target.display());
    }
    println!("Edit the file with your credentials, then run `rausu` to start the server.");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tmp_path(suffix: &str) -> PathBuf {
        std::env::temp_dir().join(format!(
            "rausu_init_test_{}_{}.yaml",
            suffix,
            std::process::id()
        ))
    }

    #[test]
    fn test_write_template_creates_file() {
        let path = tmp_path("create");
        let _ = std::fs::remove_file(&path); // ensure clean state
        write_template(&path, false).expect("should create file");
        assert!(path.exists());
        let contents = std::fs::read_to_string(&path).unwrap();
        assert!(contents.contains("server:"));
        assert!(contents.contains("logging:"));
        assert!(contents.contains("models:"));
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn test_write_template_no_overwrite_without_force() {
        let path = tmp_path("noforce");
        std::fs::write(&path, "existing content").unwrap();
        let result = write_template(&path, false);
        assert!(result.is_err(), "should return error without --force");
        assert_eq!(
            std::fs::read_to_string(&path).unwrap(),
            "existing content",
            "file must not be modified"
        );
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn test_write_template_force_overwrites() {
        let path = tmp_path("force");
        std::fs::write(&path, "existing content").unwrap();
        write_template(&path, true).expect("should overwrite with --force");
        let contents = std::fs::read_to_string(&path).unwrap();
        assert!(contents.contains("server:"), "file should be the template");
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn test_run_init_creates_file() {
        let path = tmp_path("run_init");
        let _ = std::fs::remove_file(&path);
        run_init(Some(path.to_str().unwrap()), false).expect("run_init should succeed");
        assert!(path.exists());
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn test_run_init_no_overwrite_without_force() {
        let path = tmp_path("run_init_noforce");
        std::fs::write(&path, "keep me").unwrap();
        run_init(Some(path.to_str().unwrap()), false).expect("run_init exits cleanly");
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "keep me");
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn test_run_init_force_overwrites() {
        let path = tmp_path("run_init_force");
        std::fs::write(&path, "keep me").unwrap();
        run_init(Some(path.to_str().unwrap()), true).expect("run_init --force should succeed");
        let contents = std::fs::read_to_string(&path).unwrap();
        assert!(contents.contains("server:"));
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn test_config_template_is_valid_yaml() {
        // Minimal check: ensure the template doesn't panic serde_yaml-style
        // We check key strings are present and the file starts with a comment.
        assert!(CONFIG_TEMPLATE.starts_with('#'));
        assert!(CONFIG_TEMPLATE.contains("server:"));
        assert!(CONFIG_TEMPLATE.contains("port:"));
        assert!(CONFIG_TEMPLATE.contains("logging:"));
        assert!(CONFIG_TEMPLATE.contains("models:"));
        assert!(CONFIG_TEMPLATE.contains("chatgpt-subscription"));
        assert!(CONFIG_TEMPLATE.contains("github-copilot"));
        assert!(CONFIG_TEMPLATE.contains("deepseek"));
        assert!(CONFIG_TEMPLATE.contains("ollama"));
    }
}
